### ISSUE TITLE
Use current session with Requests

### ISSUE THREAD

**Issue by simogeo** [rmccue/Requests#159]
Hi,

Requests for PHP seems really nice. Thanks for the great work !

I want to run it inside my script using user logged-in session. I thought, that could be the way to go :  

```php
include('../lib/vendor/Requests/library/Requests.php');
Requests::register_autoloader();

$options = array('cookies' => array(session_name() => session_id()));
$rSession = new Requests_Session(SITE_ROOT_URL, array(), array(), $options);
$response = $rSession->get('index.php?foo=bar&id=2789');

var_dump($response->status_code);
```

but this returns the following error : 

```txt
Fatal error: Uncaught exception 'Requests_Exception' with message 'cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received' in /path/to/applib/vendor/Requests/library/Requests/Transport/cURL.php:291 Stack trace: #0 /path/to/applib/vendor/Requests/library/Requests/Transport/cURL.php(126): Requests_Transport_cURL->process_response(false, Array) #1 /path/to/applib/vendor/Requests/library/Requests.php(325): 
Requests_Transport_cURL->request('http://localhos...', Array, NULL, Array) #2 /path/to/applib/vendor/Requests/library/Requests/Session.php(205): Requests::request('http://localhos...', Array, NULL, 'GET', Array) #3 /path/to/applib/vendor/Requests/library/Requests/Session.php(132): 
Requests_Session->request('index.php?rub=p...', Array, NULL, 'GET', Array) #4 /path/to/appexport/phpsql.process.project.php(124): Requests_Session->get('index.php?rub=p...') #5 /path/to/appexport/report. in /path/to/applib/vendor/Requests/library/Requests/Transport/cURL.php on line 291
```

Any help would be appreciated ! Thanks !

**Comment by rmccue** [comment]
Sorry for the delay here. It looks like your code is correct, but the request is just timing out. Do you get the same with a regular `Requests::get( SITE_ROOT_URL . '/index.php?foo=bar&id=2789' )`?

**Comment by simogeo** [comment]
Hi, 

I'm not really on that right now. But of course, the regular `Requests::get()` worked well !
