### ISSUE TITLE
Using PUT request

### ISSUE THREAD

**Issue by gamersalpha** [rmccue/Requests#341]
Hello i m started using yousign to do request with it but at this step i m stuck with PUT :

https://staging-dev.yousign.com/#/procedureCreate?id=start-the-procedure

![image](https://user-images.githubusercontent.com/32466950/57950563-ed911e80-78e7-11e9-87f8-661d4e5124a2.png)

this my code  :   

```
//Executer la procédure :

	$url = ('https://staging-api.yousign.com'.$idProcedures);
     	$data = array(    
				"start"=>  true
	    		
	);
	
	$response = Requests::PUT($url, $headers,json_encode($data));
	$idFileObject = json_decode($response->body);
	var_dump($idFileObject);

```
and not working : 
```
PHP Warning:  Illegal string offset 'type' in v2/vendor/rmccue/requests/library/Requests.php on line 359
PHP Warning:  array_merge(): Argument #2 is not an array in v2/vendor/rmccue/requests/library/Requests.php on line 361
PHP Notice:  Undefined index: auth in v2/vendor/rmccue/requests/library/Requests.php on line 571
PHP Notice:  Undefined index: auth in v2/vendor/rmccue/requests/library/Requests.php on line 574
PHP Notice:  Undefined index: auth in v2/vendor/rmccue/requests/library/Requests.php on line 575
PHP Fatal error:  Uncaught Error: Call to a member function register() on null in v2/vendor/rmccue/requests/library/Requests.php:575
Stack trace:
#0 v2/vendor/rmccue/requests/library/Requests.php(363): Requests::set_defaults('https://staging...', Array, NULL, 'GET', Array)
#1 v2/vendor/rmccue/requests/library/Requests.php(231): Requests::request('https://staging...', Array, NULL, 'GET', Array)
#2 v2/Cookbook.php(92): Requests::get('https://staging...', Array, '{"start":true}')
#3 {main}
  thrown in v2/vendor/rmccue/requests/library/Requests.php on line 575
```

how do a put please ?

**Comment by datagutten** [comment]
Your code seems correct, but somehow your third argument to `Requests::Put` which should be `$data` according to the [documentation](http://requests.ryanmccue.info/api/class-Requests.html#_put) somehow is parsed as `$options`.
Are you using the latest stable version of Requests? I tested your code with v1.7.0 and got no problems.

**Comment by rmccue** [comment]
Sorry, I can't offer support on this repo.
