### ISSUE TITLE
Cannot send payload/data when performing a delete.

### ISSUE THREAD

**Issue by toolbox1972** [rmccue/Requests#347]
Attempting to perform a [Requests::delete]. Observing the source code in package Requests, it seem that the variable for [$data] does not exists. Path in Requests[Requests/library/Requests.php] line 242-246.

I am able to perform [delete] both with plain curl, and with programming language "R" (package httr).

```
$response_delete = Requests::delete(
    $url = "https://api-accept2.bolagsverket.se/testapi/hantera-arsredovisningsprenumerationer/v1.0/handelseprenumeration" ,
    $headers = array('Content-Type' => 'application/json; charset=UTF-8'),
    $data = array(
         "url"   => "programvaruleverantor.example.com/arsredovisning/handelser/",
         "orgnr" => "5563331494"
    )
);

var_dump($response_delete);
```

Error message:
```
PHP Fatal error:  Uncaught Requests_Exception: cURL error 61: Unrecognized content encoding type. libcurl understands deflate, gzip content encodings. in /repos/git/software/annual_report/packages/Requests/library/Requests/Transport/cURL.php:422
Stack trace:
#0 /repos/git/software/annual_report/packages/Requests/library/Requests/Transport/cURL.php(177): Requests_Transport_cURL->process_response('', Array)
#1 /repos/git/software/annual_report/packages/Requests/library/Requests.php(379): Requests_Transport_cURL->request('https://api-acc...', Array, NULL, Array)
#2 /repos/git/software/annual_report/packages/Requests/library/Requests.php(245): Requests::request('https://api-acc...', Array, NULL, 'DELETE', Array)
#3 /repos/git/software/annual_report/languages/3_php/requests/61_bug.php(28): Requests::delete('https://api-acc...', Array, Array)
#4 {main}
  thrown in /repos/git/software/annual_report/packages/Requests/library/Requests/Transport/cURL.php on line 422
```
The working code that original sent the POST:

```
 $response_post = Requests::post(
     $url = "https://api-accept2.bolagsverket.se/testapi/hantera-arsredovisningsprenumerationer/v1.0/handelseprenumeration",
     $headers = array('Content-Type' => 'application/json; charset=UTF-8'),
     $data = "{
         \"prenumerationer\":
         [
             {
                 \"url\":\"programvaruleverantor.example.com/arsredovisning/handelser/\",
                 \"orgnr\":\"5563331494\"
             }
         ]

     }"
 );

var_dump($response_post);
```

**Comment by rmccue** [comment]
You need to use `Requests::request` to send GET, DELETE, or OPTIONS requests with bodies, rather than using the convenience methods.
