### ISSUE TITLE
Deprecation issue with implode() (PHP 7.4)

### ISSUE THREAD

**Issue by colincameron** [rmccue/Requests#391]
PHP 7.4 deprecated passing parameters to implode() in reverse order: https://www.php.net/manual/en/migration74.deprecated.php

Since upgrading to 7.4, I am now seeing deprecation warnings using this library.

> Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /app/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php on line 195

**Comment by jrfnl** [comment]
This has already been fixed in #346, there just hasn't been a release since unfortunately.

**Comment by colincameron** [comment]
Thanks - is there any plans for when a new version might be released? It's been nearly 4 years since v1.7.0.

**Comment by jrfnl** [comment]
I honestly don't know. I've been hoping for a release for quite a while now.

**Comment by ottok** [comment]
This is now fatal in PHP 8.0. Noticed while running wp-cli, which uses rmccue/Requests:

```
# wp-check-php-version 
==> Check PHP backends:
Found PHP mode definition: php8.0 in '/data/wordpress/nginx/php.conf'
Using php8.0
php8.0

# wp --version
WP-CLI 2.4.0

# wp core update
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php:195
Stack trace:
#0 phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php(195): implode()
#1 phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests.php(379): Requests_Transport_fsockopen->request()
#2 /data/wordpress/htdocs/wordpress/wp-includes/class-http.php(394): Requests::request()
#3 /data/wordpress/htdocs/wordpress/wp-includes/class-http.php(608): WP_Http->request()
#4 /data/wordpress/htdocs/wordpress/wp-includes/http.php(179): WP_Http->post()
#5 /data/wordpress/htdocs/wordpress/wp-includes/update.php(159): wp_remote_post()
#6 phar:///usr/local/bin/wp-cli/vendor/wp-cli/core-command/src/Core_Command.php(1076): wp_version_check()
#7 [internal function]: Core_Command->update()
#8 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func()
#9 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}()
#10 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(451): call_user_func()
#11 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(371): WP_CLI\Dispatcher\Subcommand->invoke()
#12 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(394): WP_CLI\Runner->run_command()
#13 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1160): WP_CLI\Runner->run_command_and_exit()
#14 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#15 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process()
#16 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#17 phar:///usr/local/bin/wp-cli/php/boot-phar.php(11): include('...')
#18 /usr/local/bin/wp-cli(4): include('...')
#19 {main}
  thrown in phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php on line 195
Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php:195
Stack trace:
#0 phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php(195): implode()
#1 phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests.php(379): Requests_Transport_fsockopen->request()
#2 /data/wordpress/htdocs/wordpress/wp-includes/class-http.php(394): Requests::request()
#3 /data/wordpress/htdocs/wordpress/wp-includes/class-http.php(608): WP_Http->request()
#4 /data/wordpress/htdocs/wordpress/wp-includes/http.php(179): WP_Http->post()
#5 /data/wordpress/htdocs/wordpress/wp-includes/update.php(159): wp_remote_post()
#6 phar:///usr/local/bin/wp-cli/vendor/wp-cli/core-command/src/Core_Command.php(1076): wp_version_check()
#7 [internal function]: Core_Command->update()
#8 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func()
#9 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}()
#10 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(451): call_user_func()
#11 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(371): WP_CLI\Dispatcher\Subcommand->invoke()
#12 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(394): WP_CLI\Runner->run_command()
#13 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1160): WP_CLI\Runner->run_command_and_exit()
#14 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#15 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process()
#16 phar:///usr/local/bin/wp-cli/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#17 phar:///usr/local/bin/wp-cli/php/boot-phar.php(11): include('...')
#18 /usr/local/bin/wp-cli(4): include('...')
#19 {main}
  thrown in phar:///usr/local/bin/wp-cli/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php on line 195
Error: There has been a critical error on your website.Learn more about debugging in WordPress. There has been a critical error on your website.
```

**Comment by jrfnl** [comment]
I'm closing this issue as the fix is already merged. A new release is expected soonish...

**Comment by whalehub** [comment]
@jrfnl Any update on a new release?

**Comment by jrfnl** [comment]
@whalehub Soon, very soon... (we just had a call about it today)
